### ISSUE TITLE
ImportError: cannot import name 'SupportsIndex' from 'typing_extensions' (//anaconda3/lib/python3.7/site-packages/typing_extensions.py)

### ISSUE THREAD

**Issue by makkimaki** [shibuiwilliam/ml-system-in-actions#10]
python3.7.3  
Mac OS Mojave  
pyenv使用  
の元で、`$make train`実行時に以下のエラーが出ました。
```
mlflow run . --no-conda
Notice: failed to import Git (the git executable is probably not on your PATH), so Git SHA is not available. Error: cannot import name 'SupportsIndex' from 'typing_extensions' (//anaconda3/lib/python3.7/site-packages/typing_extensions.py)
2021/10/04 22:57:33 WARNING mlflow.tracking.context.git_context: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: cannot import name 'SupportsIndex' from 'typing_extensions' (//anaconda3/lib/python3.7/site-packages/typing_extensions.py)
Traceback (most recent call last):
  File "//anaconda3/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "//anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "//anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "//anaconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "//anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "//anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "//anaconda3/lib/python3.7/site-packages/mlflow/cli.py", line 181, in run
    run_id=run_id,
  File "//anaconda3/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 304, in run
    synchronous=synchronous,
  File "//anaconda3/lib/python3.7/site-packages/mlflow/projects/__init__.py", line 99, in _run
    experiment_id,
  File "//anaconda3/lib/python3.7/site-packages/mlflow/projects/backend/local.py", line 52, in run
    run_id, project_uri, experiment_id, work_dir, version, entry_point, params
  File "//anaconda3/lib/python3.7/site-packages/mlflow/projects/utils.py", line 221, in get_or_create_run
    return _create_run(uri, experiment_id, work_dir, version, entry_point, parameters)
  File "//anaconda3/lib/python3.7/site-packages/mlflow/projects/utils.py", line 252, in _create_run
    repo_url = _get_git_repo_url(work_dir)
  File "//anaconda3/lib/python3.7/site-packages/mlflow/projects/utils.py", line 69, in _get_git_repo_url
    from git import Repo
  File "//anaconda3/lib/python3.7/site-packages/git/__init__.py", line 8, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "//anaconda3/lib/python3.7/site-packages/git/exc.py", line 15, in <module>
    from git.types import PathLike
  File "//anaconda3/lib/python3.7/site-packages/git/types.py", line 13, in <module>
    from typing_extensions import (Final, Literal, SupportsIndex,                           # noqa: F401
ImportError: cannot import name 'SupportsIndex' from 'typing_extensions' (//anaconda3/lib/python3.7/site-packages/typing_extensions.py)
make: *** [train] Error 1
```

typingExtensionsとSupportIndexに関するエラーに見えますがpythonのバージョンなど関係あるでしょうか。。
まだ解消できてないですが報告します。

**Comment by shibuiwilliam** [comment]
@makkimaki 
ご連絡ありがとうございます。
ちょっとこちらでも調査してみます。再現できなかった場合は情報提供を依頼するかもしれませんが、ご容赦ください。

**Comment by shibuiwilliam** [comment]
@makkimaki 
私の環境では問題ないですが、ご利用のPythonは3.7ですか？
プログラムはPython3.8以降で検証していることと、Python3.7のtyping_extentionsでは不具合がある報告があるので、Python3.8以降にアップデートして試していただけないでしょうか？

**Comment by makkimaki** [comment]
@shibuiwilliam お手数かけました。Python3.7のtyping_extensionsの不具合に起因する可能性ですね。3.8で試します。ありがとうございます。
